language: ruby
services: postgresql
before_install:
- nvm install $(npm run -s version)
- nvm use $(npm run -s version)
install:
- bin/setup
cache: bundler
deploy:
  provider: script
  skip_cleanup: true
  script: rvm $(< .ruby-version) do bin/deploy
  on:
    repo: oeco-architectes/oeco
    tags: true
