language: ruby
services: postgresql
before_install:
- nvm install 6
- nvm use 6
install:
- bin/setup
cache: bundler
deploy:
  provider: script
  skip_cleanup: true
  script: rvm $(< .ruby-version) do bin/deploy
  on:
    repo: oeco-architectes/oeco
    tags: true
