# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8589e6bddca326b9afaff8eb1fd42f90614c2c256b60f9e8344112c2df563736d6e51f6c7691fd076fd069b8a4137884cfde5ccf3792ed9301d5669504f44a9

test:
  secret_key_base: c7f3513a19302a8dfa6931888b1e0dfbefe6ab6a9017f60a8b689490a46f19878a0705f5a67995cc58e88c0c6eae63a86f54833112e0891cc1cfb641cde040e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
