data:
  news_img: http://lorempixel.com/%{width}/%{height}/cats/?%{slug}
  project_img: http://lorempixel.com/%{width}/%{height}/cats/?%{slug}
facebook:
  page_url: https://www.facebook.com/OECO-Architectes-143451935789053/
